# Generated by Django 5.1.2 on 2024-11-06 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_alter_buyer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='phone_number',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона (например, +79991234567).', regex='^\\+7\\d{10}$')]),
        ),
    ]
